name: Check - JavaScript

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'web/src/**'
      - 'web/package.json'
      - 'web/package-lock.json'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'web/package.json'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - run: npm ci
        working-directory: 'web/'

      - name: Check formatted & Lint
        run: |
          npm run check
        working-directory: 'web/'

      - name: Test
        run: |
          npm t
        working-directory: 'web/'

      - name: Check build
        run: |
          npm run build
        working-directory: 'web/'
